### ISSUE TITLE
Frontend side not working?

### ISSUE THREAD

**Issue by tarlepp** [UniBot/unibot-logs#1]
Seems like this plugin frontend side get only "loading data...", nothing else?

**Comment by ProLoser** [comment]
This line should probably just be ng-hide="logs" instead of the length
property. Since chances are there are no logs. I don't really use this
plugin that much because I was afraid it was causing the bot to crash and
wanted to make it more efficient. If you have batarang, you can inspect the
scope and confirm that a response came, it's just probably an empty array.

On Sat, Jan 3, 2015 at 1:59 PM, Tarmo Leppänen notifications@github.com
wrote:

> Seems like this plugin frontend side get only "loading data...", nothing
> else?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UniBot/unibot-logs/issues/1.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by tarlepp** [comment]
Still not working...
